version: "3.7"

services:
  dofitfront:
    image: hub.yohannbiglia.fr/armando-project/front:latest
    restart: always
    networks:
      - traefik-proxy
    volumes:
      - ./docker/prod/app/nginx:/etc/nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.dofitfront.rule=Host(`dofit.yohannbiglia.fr`)
      - traefik.http.routers.dofitfront.entrypoints=websecure
      - traefik.http.routers.dofitfront.tls=true
      - traefik.http.routers.dofitfront.tls.certresolver=letsencrypt

networks:
  traefik-proxy:
    name: "traefik-proxy"
